<a href="https://colab.research.google.com/github/derekriceX/RSM/blob/main/Kutz_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
x = [1,2,3]
x


[1, 2, 3]

In [ ]:
y = np.array([1,2,3])
y

array([1, 2, 3])

In [ ]:
y.ndim

1

In [ ]:
z=tf.constant([1,2,3])
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
print(z)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
z_2dim = tf.reshape(z,(3,1))
z_2dim

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [ ]:
w = np.array([
                [
                [1,2],
                [2,3],
                [3,4]
                ],
                [
               [3,4],
                [5,6],
                [7,8]
               ]
               ])
w
print(w.shape)
print(w.ndim)

(2, 3, 2)
3
