In [2]:
import torch
import numpy as np 

In [7]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [4]:
# change a to a numpy array 

b = np.array([0.5,0.4,2])

print(b)


[0.5 0.4 2. ]


In [5]:
c = torch.tensor(b)
print(c)

tensor([0.5000, 0.4000, 2.0000], dtype=torch.float64)


In [6]:
# how to go from tensor to numpy array 

d = a.numpy()
b

array([0.5, 0.4, 2. ])

In [8]:
print(type(b))

<class 'numpy.ndarray'>


In [9]:
print(type(d))

<class 'numpy.ndarray'>


In [10]:
print(type(a))

<class 'torch.Tensor'>


In [13]:
# what is the tensor is located in the GPU 

if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5,device=device)
    print(x)
